### ISSUE TITLE
Assign values for each symptom dummy variable

### ISSUE THREAD

**Issue by mbcann01** [brad-cannell/detect_pilot_test_1y#21]
See e4af061f26c6e1523ecbdbea337f2a78a5f6bc7c

Starting on line 90 of table_medstar_epcr_patient_symtoms.Rmd, we need to assign 0's and 1's to each of the dummy variables we created for symptoms.

**Comment by mbcann01** [comment]
Fixed in c22fdfa8c97e89d39128eced13db9ba601df4a43

@jared-g-wiegand please take a look and make sure everything is working as expected.

**Comment by jared-g-wiegand** [comment]
Yes this works for me now! Thank you @mbcann01
