### ISSUE TITLE
Incident Complaint v Symptoms Table

### ISSUE THREAD

**Issue by jared-g-wiegand** [brad-cannell/detect_pilot_test_1y#23]
Hi @mbcann01 , 

I am having some trouble with this code.  I just pushed what I have gotten so far to the develop-medical-conditions branch.  Starting at line 172, I do not know how to create the table since we are looking for the frequency of the cells, but the rows are incident complaints and columns are the totals from each individual symptom column.

**Comment by mbcann01** [comment]
Hey @jared-g-wiegand ,

Sorry for the delay. I'm looking at this now.

**Comment by mbcann01** [comment]
Hey @jared-g-wiegand ,

I went ahead and finished this analysis. Please look it over and let me know what does/doesn't make sense and if anything jumps out at you.
