### ISSUE TITLE
Create codebooks

### ISSUE THREAD

**Issue by mbcann01** [brad-cannell/detect_pilot_test_1y#34]
# Overview

After merging and wrangling the APS and MedStar data (#33), we need to create a codebook (or codebooks) for the data using [codebookr](https://github.com/brad-cannell/codebookr)

**Comment by corvidfox** [comment]
This week I was able to get a preliminary codebook for the MedStar data, which is in pull request #45

**Comment by corvidfox** [comment]
This week I have a preliminary codebook for the APS data, which is in pull request #47

**Comment by corvidfox** [comment]
As of pull request #50, codebooks for both the APS and MedStar data have been completed. Codebooks for all 3 merge data sets have been created.
